import test from 'node:test';import assert from 'node:assert/strict';import { promises as fs } from 'node:fs';import os from 'node:os';import path from 'node:path';
import { indexProject } from '../src/indexer.mjs';import { getPermissionProfile,requirePermission } from '../src/permissions.mjs';import { redact,appendSession,exportSession } from '../src/sessions.mjs';import { completion } from '../src/completions.mjs';import { serveAgent } from '../src/agent-protocol.mjs';import { McpClient } from '../src/mcp.mjs';import { panel,strip } from '../src/ui.mjs';import { Readable,Writable } from 'node:stream';
async function temp(){return fs.mkdtemp(path.join(os.tmpdir(),'ultron-'));}
test('indexer obeys ignore files',async()=>{const root=await temp();await fs.writeFile(path.join(root,'.gitignore'),'secret.txt\n');await fs.writeFile(path.join(root,'ok.js'),'ok');await fs.writeFile(path.join(root,'secret.txt'),'no');const index=await indexProject(root);assert.ok(index.files.some(x=>x.path==='ok.js'));assert.ok(!index.files.some(x=>x.path==='secret.txt'));});
test('read-only profile blocks writes',()=>{const p=getPermissionProfile('read-only');assert.throws(()=>requirePermission(p,'fileWrite','write'),/denied/);});
test('session redaction removes credentials',()=>{assert.doesNotMatch(redact('api_key=super-secret token=abc123'),/super-secret|abc123/);});
test('sessions persist securely and export JSON',async()=>{const dir=await temp();await appendSession('s1',{type:'turn',prompt:'token=secret',text:'ok'},dir);const records=JSON.parse(await exportSession('s1',{format:'json',dir}));assert.equal(records[0].type,'turn');assert.doesNotMatch(records[0].prompt,/token=secret/);if(process.platform!=='win32'){const mode=(await fs.stat(path.join(dir,'s1.jsonl'))).mode&0o777;assert.equal(mode,0o600);}});
test('all shell completions generate',()=>{for(const shell of ['bash','zsh','fish','powershell'])assert.match(completion(shell),/ultron/);});
test('JSONL agent transport initializes and prompts',async()=>{const incoming=Readable.from(['{"jsonrpc":"2.0","id":1,"method":"initialize"}\n','{"jsonrpc":"2.0","id":2,"method":"prompt","params":{"prompt":"hi"}}\n','{"jsonrpc":"2.0","id":3,"method":"shutdown"}\n']);let text='';const outgoing=new Writable({write(chunk,enc,cb){text+=chunk.toString();cb();}});await serveAgent({input:incoming,output:outgoing,ask:async p=>({text:p.prompt})});const rows=text.trim().split('\n').map(JSON.parse);assert.equal(rows[0].result.protocol,'ultron-jsonl/1');assert.equal(rows[1].result.text,'hi');});
test('MCP client initializes, lists, and calls tools',async()=>{const root=await temp(),server=path.join(root,'server.mjs');await fs.writeFile(server,`import readline from 'node:readline';const rl=readline.createInterface({input:process.stdin});rl.on('line',line=>{const m=JSON.parse(line);if(m.id){let result=m.method==='initialize'?{protocolVersion:'2025-03-26'}:m.method==='tools/list'?{tools:[{name:'echo'}]}:{content:[{type:'text',text:m.params.arguments.value}]};console.log(JSON.stringify({jsonrpc:'2.0',id:m.id,result}));}});`);const client=new McpClient(process.execPath,[server]);try{await client.start();const tools=await client.listTools();assert.equal(tools.tools[0].name,'echo');const called=await client.callTool('echo',{value:'ok'});assert.equal(called.content[0].text,'ok');}finally{client.close();}});
test('panel remains bounded on narrow terminals',()=>{for(const row of panel('A long accessible title',['a'.repeat(100)],36).split('\n')){const clean=strip(row);assert.ok(clean.length<=36,`${clean.length}:${JSON.stringify(clean)}`);}});

