import test from 'node:test';
import assert from 'node:assert/strict';
import { providers, getProvider, ProviderHttpError } from '../src/providers.mjs';

function headers(values = {}) { return { get: name => values[name.toLowerCase()] ?? values[name] ?? null }; }
function response(body, { ok = true, status = 200, headerValues = {} } = {}) { return { ok, status, statusText: '', headers: headers(headerValues), text: async () => JSON.stringify(body) }; }
function sseResponse(frames, headerValues = {}) { const bytes = new TextEncoder().encode(frames); return { ok: true, status: 200, headers: headers(headerValues), body: new ReadableStream({ start(controller) { controller.enqueue(bytes); controller.close(); } }) }; }

test('required providers exist', () => { for (const name of ['openai', 'anthropic', 'kimi', 'custom', 'kiro', 'claude-code', 'openclaw']) assert.ok(providers[name]); });
test('unknown provider fails clearly', () => assert.throws(() => getProvider('missing'), /Unknown provider/));
test('direct providers advertise hardening capabilities', () => { for (const name of ['openai', 'anthropic', 'kimi', 'custom']) assert.deepEqual(providers[name].capabilities, { streaming: true, cancellation: true, retries: true, models: true, usage: true, conversation: true }); });
test('openai forwards structured conversation history',async()=>{process.env.OPENAI_API_KEY='test';let sent;await providers.openai.askDetailed('latest',{messages:[{role:'system',content:'safe'},{role:'user',content:'first'},{role:'assistant',content:'reply'},{role:'user',content:'latest'}],fetchImpl:async(url,options)=>{sent=JSON.parse(options.body);return response({output_text:'ok'})}});assert.equal(sent.input.length,4);assert.equal(sent.input[1].content,'first');delete process.env.OPENAI_API_KEY});
test('openai adapter parses response and usage', async () => { process.env.OPENAI_API_KEY = 'test'; const result = await providers.openai.askDetailed('hello', { fetchImpl: async () => response({ output_text: 'ok', usage: { input_tokens: 2, output_tokens: 1 } }) }); assert.equal(result.text, 'ok'); assert.equal(result.usage.inputTokens, 2); delete process.env.OPENAI_API_KEY; });
test('openai streaming emits deltas and usage', async () => { process.env.OPENAI_API_KEY = 'test'; const chunks = []; const body = 'event: response.output_text.delta\ndata: {"type":"response.output_text.delta","delta":"hel"}\n\nevent: response.output_text.delta\ndata: {"type":"response.output_text.delta","delta":"lo"}\n\nevent: response.completed\ndata: {"type":"response.completed","response":{"usage":{"input_tokens":3,"output_tokens":2}}}\n\n'; const result = await providers.openai.askDetailed('hello', { stream: true, onToken: x => chunks.push(x), fetchImpl: async () => sseResponse(body) }); assert.equal(result.text, 'hello'); assert.deepEqual(chunks, ['hel', 'lo']); assert.equal(result.usage.outputTokens, 2); delete process.env.OPENAI_API_KEY; });
test('anthropic streaming parses text and usage', async () => { process.env.ANTHROPIC_API_KEY = 'test'; const body = 'event: message_start\ndata: {"message":{"usage":{"input_tokens":4}}}\n\nevent: content_block_delta\ndata: {"delta":{"type":"text_delta","text":"ok"}}\n\nevent: message_delta\ndata: {"usage":{"output_tokens":1}}\n\n'; const result = await providers.anthropic.askDetailed('hello', { stream: true, fetchImpl: async () => sseResponse(body) }); assert.equal(result.text, 'ok'); assert.equal(result.usage.inputTokens, 4); assert.equal(result.usage.outputTokens, 1); delete process.env.ANTHROPIC_API_KEY; });
test('429 retries then succeeds', async () => { process.env.OPENAI_API_KEY = 'test'; let calls = 0; const result = await providers.openai.askDetailed('hello', { maxRetries: 1, retryBaseMs: 1, retryMaxMs: 1, fetchImpl: async () => ++calls === 1 ? response({ error: { message: 'slow down' } }, { ok: false, status: 429, headerValues: { 'retry-after': '0' } }) : response({ output_text: 'ok' }) }); assert.equal(result.text, 'ok'); assert.equal(calls, 2); delete process.env.OPENAI_API_KEY; });
test('non-retryable error is structured', async () => { process.env.OPENAI_API_KEY = 'test'; await assert.rejects(() => providers.openai.askDetailed('hello', { fetchImpl: async () => response({ error: { message: 'bad request' } }, { ok: false, status: 400 }) }), error => error instanceof ProviderHttpError && error.status === 400); delete process.env.OPENAI_API_KEY; });
test('model discovery uses models endpoint', async () => { process.env.OPENAI_API_KEY = 'test'; let url; const models = await providers.openai.listModels({ fetchImpl: async value => { url = value; return response({ data: [{ id: 'm1' }] }); } }); assert.match(url, /\/models$/); assert.equal(models[0].id, 'm1'); delete process.env.OPENAI_API_KEY; });
