import { spawn } from 'node:child_process';
export class McpClient {
  constructor(command, args = [], { cwd = process.cwd(), env = process.env, timeoutMs = 30000 } = {}) { this.command = command; this.args = args; this.cwd = cwd; this.env = env; this.timeoutMs = timeoutMs; this.nextId = 1; this.pending = new Map(); }
  async start() { if (this.child) return; this.child = spawn(this.command, this.args, { cwd: this.cwd, env: this.env, shell: false, stdio: ['pipe', 'pipe', 'pipe'] }); let buffer = ''; this.child.stdout.setEncoding('utf8'); this.child.stdout.on('data', chunk => { buffer += chunk; let i; while ((i = buffer.indexOf('\n')) >= 0) { const line = buffer.slice(0, i).trim(); buffer = buffer.slice(i + 1); if (!line) continue; try { const msg = JSON.parse(line), pending = this.pending.get(msg.id); if (pending) { this.pending.delete(msg.id); msg.error ? pending.reject(new Error(msg.error.message || 'MCP error')) : pending.resolve(msg.result); } } catch {} } }); this.child.on('exit', code => { for (const pending of this.pending.values()) pending.reject(new Error(`MCP server exited ${code}`)); this.pending.clear(); }); await this.request('initialize', { protocolVersion: '2025-03-26', capabilities: {}, clientInfo: { name: 'ultron-cli', version: '0.3.0' } }); this.notify('notifications/initialized', {}); }
  request(method, params = {}) { const id = this.nextId++; return new Promise((resolve, reject) => { const timer = setTimeout(() => { this.pending.delete(id); reject(new Error(`MCP request timed out: ${method}`)); }, this.timeoutMs); this.pending.set(id, { resolve: value => { clearTimeout(timer); resolve(value); }, reject: error => { clearTimeout(timer); reject(error); } }); this.child.stdin.write(`${JSON.stringify({ jsonrpc: '2.0', id, method, params })}\n`); }); }
  notify(method, params = {}) { this.child.stdin.write(`${JSON.stringify({ jsonrpc: '2.0', method, params })}\n`); }
  listTools() { return this.request('tools/list'); } callTool(name, args = {}) { return this.request('tools/call', { name, arguments: args }); }
  close() { this.child?.kill('SIGTERM'); }
}
