import { promises as fs } from 'node:fs';
import path from 'node:path'; import os from 'node:os'; import crypto from 'node:crypto';
const SENSITIVE_KEY = /^(?:api[_-]?key|authorization|token|secret|password)$/i;
const SECRET_PATTERNS = [/(Bearer\s+)[A-Za-z0-9._~+\/-]+/gi, /((?:api[_-]?key|token|secret|password)\s*[=:]\s*)[^\s,;"']+/gi, /\b(sk-[A-Za-z0-9_-]{12,})\b/g];
function redactString(value) { let text = value; for (const pattern of SECRET_PATTERNS) text = text.replace(pattern, (_, prefix = '') => `${prefix}[REDACTED]`); return text; }
function redactValue(value) { if (typeof value === 'string') return redactString(value); if (Array.isArray(value)) return value.map(redactValue); if (value && typeof value === 'object') return Object.fromEntries(Object.entries(value).map(([key,item]) => [key, SENSITIVE_KEY.test(key) ? '[REDACTED]' : redactValue(item)])); return value; }
export function redact(value) { return typeof value === 'string' ? redactString(value) : JSON.stringify(redactValue(value)); }
export function sessionId() { return `${Date.now()}-${crypto.randomBytes(4).toString('hex')}`; }
export function sessionPath(id, dir = process.env.ULTRON_SESSION_DIR || path.join(os.homedir(), '.ultron', 'sessions')) { if (!/^[A-Za-z0-9._-]+$/.test(id)) throw new Error('Invalid session id'); return path.join(dir, `${id}.jsonl`); }
export async function appendSession(id, event, dir) { const file = sessionPath(id, dir); await fs.mkdir(path.dirname(file), { recursive: true, mode: 0o700 }); const record = { version: 1, timestamp: new Date().toISOString(), ...event }; await fs.appendFile(file, `${redact(record)}\n`, { mode: 0o600 }); await fs.chmod(file, 0o600); return file; }
export async function loadSession(id, dir) { const content = await fs.readFile(sessionPath(id, dir), 'utf8'); return content.split(/\r?\n/).filter(Boolean).map(JSON.parse); }
export async function exportSession(id, { format = 'jsonl', destination, dir } = {}) { const source = sessionPath(id, dir), content = await fs.readFile(source, 'utf8'); if (format === 'jsonl') { if (destination) await fs.writeFile(destination, content, { mode: 0o600 }); return destination || content; } const records = content.split(/\r?\n/).filter(Boolean).map(JSON.parse); const output = format === 'json' ? JSON.stringify(records, null, 2) : records.map(r => `## ${r.timestamp} · ${r.type || 'event'}\n\n${r.prompt ? `**Prompt:** ${r.prompt}\n\n` : ''}${r.text || ''}`).join('\n\n'); if (destination) await fs.writeFile(destination, output, { mode: 0o600 }); return destination || output; }
